### ISSUE TITLE
Getting error when trying to call latest falcon-linux-install.sh file through ansible code

### ISSUE THREAD

**Issue by koushik527** [CrowdStrike/falcon-scripts#353]
I am getting error when trying to call the falcon-linux-install.sh file through ansible code below

- name Run Falcon installation 
  environment:
     FALCON_CLIENT_ID: passing client ID
     FALCON_CLIENT_SECRET: passing secret
  shell: |
     export FALCON_CLIENT_ID=value
     export FALCON_CLIENT_SECRET= value
     opt/falcon-linux-install.sh

Getting error as below

Fatal error - Unable to obtain Crowdstrike Falcon OAuth Token .Double check your credentials and/or ensure you set the correct cloud region.

I am not sure what I am missing..could anyone guide me on this

**Comment by carlosmmatos** [comment]
@koushik527 thanks for opening up an issue. Question for you, why aren't you just using our [Ansible collection](https://github.com/CrowdStrike/ansible_collection_falcon) to do this instead of trying to wrap Ansible around this bash script?

Here's an example of how you can use our Ansible collection to install/configure the sensor for you using pure Ansible:
```yaml
- hosts: all
  vars:
    falcon_client_id: <FALCON_CLIENT_ID>
    falcon_client_secret: <FALCON_CLIENT_SECRET>
  roles:
  - role: crowdstrike.falcon.falcon_install
  - role: crowdstrike.falcon.falcon_configure
```

Take a look at the README's for different options you can do within our roles.
